// ASENT Image Registry — pointing to extracted image files in ./images/
export const IMAGES = {
  "al-azhar": "./images/al-azhar.jpg",
  "allied-bank": "./images/allied-bank.jpg",
  "arkadian": "./images/arkadian.jpg",
  "centerpoint": "./images/centerpoint.jpg",
  "club-house-lobby": "./images/club-house-lobby.jpg",
  "club-house": "./images/club-house.jpg",
  "exec-dining": "./images/exec-dining.jpg",
  "first-microfinance": "./images/first-microfinance.jpg",
  "fmfb-interior": "./images/fmfb-interior.jpg",
  "gilgit-interior": "./images/gilgit-interior.jpg",
  "gilgit-medical": "./images/gilgit-medical.jpg",
  "hero-mangrove-aerial": "./images/hero-mangrove-aerial.jpg",
  "hub-school": "./images/hub-school.jpg",
  "iba-admin": "./images/iba-admin.jpg",
  "iba-hostel": "./images/iba-hostel.jpg",
  "js-auditorium": "./images/js-auditorium.jpg",
  "js-center": "./images/js-center.jpg",
  "karachi-shipyard": "./images/karachi-shipyard.jpg",
  "liaquat-hospital": "./images/liaquat-hospital.jpg",
  "lnh-night": "./images/lnh-night.jpg",
  "mangrove-interior": "./images/mangrove-interior.jpg",
  "mangrove": "./images/mangrove.jpg",
  "medtronic": "./images/medtronic.jpg",
  "menzies-ras": "./images/menzies-ras.jpg",
  "mjsf-hospital": "./images/mjsf-hospital.jpg",
  "one-hoshang": "./images/one-hoshang.jpg",
  "parco": "./images/parco.jpg",
  "peace-apartments": "./images/peace-apartments.jpg",
  "peace-apartments-site": "./images/peace-apartments-naya-nazimabad.jpg",
  "rahat-residency": "./images/rahat-residency.jpg",
  "sales-center": "./images/sales-center.jpg",
  "sanofi": "./images/sanofi.jpg",
  "serena-quetta": "./images/serena-quetta.jpg",
  "serena-room": "./images/serena-room.jpg",
  "sukkur-iba": "./images/sukkur-iba.jpg",
  "usaid": "./images/usaid.jpg",
  "zaver-pc": "./images/zaver-pc.jpg",
  "logoWhite": "./images/cropped-Logo-asent.png",
  "markNavy": "./images/markNavy.png",
  "cert-agakhan": "./images/HSEcertificates/Agakhangilgit.png",
  "cert-ibasukkur": "./images/HSEcertificates/IBASUKKUR.png",
  "cert-kpt": "./images/HSEcertificates/KPT.png",
  "cert-lnh": "./images/HSEcertificates/LNH.png",
  "cert-usaid": "./images/HSEcertificates/USAID.png"
};

